// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarks.sql

package database

import (
	"context"
)

const getBookmarks = `-- name: GetBookmarks :many
SELECT
    id, name, available_amount, size, price, material, category_id, description, image_url, created_at, updated_at, is_active
FROM
    bookmarks
WHERE
    is_active = TRUE
ORDER BY
    created_at DESC
`

func (q *Queries) GetBookmarks(ctx context.Context) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvailableAmount,
			&i.Size,
			&i.Price,
			&i.Material,
			&i.CategoryID,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
