// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	ID              int32
	Name            string
	AvailableAmount int32
	Size            string
	Price           string
	Material        string
	CategoryID      int32
	Description     string
	ImageUrl        string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	IsActive        bool
}

type BookmarkCategory struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsActive  bool
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Role           int32
	Name           string
}
