// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Role           int32
}

type ZakladkaCategory struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsActive  bool
}

type Zakladki struct {
	ID              int32
	Name            string
	AvailableAmount int32
	Size            sql.NullString
	Price           string
	Material        sql.NullString
	CategoryID      int32
	Description     sql.NullString
	ImageUrl        sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	IsActive        bool
}
