// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarksLike.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserBookmarksLikes = `-- name: GetUserBookmarksLikes :many

SELECT bookmarks.id, bookmarks.name, bookmarks.available_amount, bookmarks.size, bookmarks.price, bookmarks.material, bookmarks.category_id, bookmarks.description, bookmarks.image_url, bookmarks.created_at, bookmarks.updated_at, bookmarks.is_active FROM bookmarks INNER JOIN
users_bookmarks_likes ON bookmarks.id = users_bookmarks_likes.bookmark_id
WHERE users_bookmarks_likes.user_id = $1 AND users_bookmarks_likes.is_liked = TRUE
`

func (q *Queries) GetUserBookmarksLikes(ctx context.Context, userID uuid.UUID) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, getUserBookmarksLikes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookmark
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvailableAmount,
			&i.Size,
			&i.Price,
			&i.Material,
			&i.CategoryID,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeBookmark = `-- name: LikeBookmark :one

INSERT INTO users_bookmarks_likes (user_id, bookmark_id, is_liked, reaction_type)
VALUES ($1, $2, TRUE, $3)
RETURNING user_id, bookmark_id, is_liked, reaction_type, created_at, updated_at
`

type LikeBookmarkParams struct {
	UserID       uuid.UUID
	BookmarkID   int32
	ReactionType sql.NullString
}

func (q *Queries) LikeBookmark(ctx context.Context, arg LikeBookmarkParams) (UsersBookmarksLike, error) {
	row := q.db.QueryRowContext(ctx, likeBookmark, arg.UserID, arg.BookmarkID, arg.ReactionType)
	var i UsersBookmarksLike
	err := row.Scan(
		&i.UserID,
		&i.BookmarkID,
		&i.IsLiked,
		&i.ReactionType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlikeBookmark = `-- name: UnlikeBookmark :exec

UPDATE users_bookmarks_likes
SET is_liked = FALSE
WHERE user_id = $1 AND bookmark_id = $2
RETURNING user_id, bookmark_id, is_liked, reaction_type, created_at, updated_at
`

type UnlikeBookmarkParams struct {
	UserID     uuid.UUID
	BookmarkID int32
}

func (q *Queries) UnlikeBookmark(ctx context.Context, arg UnlikeBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, unlikeBookmark, arg.UserID, arg.BookmarkID)
	return err
}
