// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bookmarksLike.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getLike = `-- name: GetLike :one

SELECT user_id, bookmark_id, is_liked, created_at, updated_at FROM users_bookmarks_likes
WHERE user_id = $1 AND bookmark_id = $2
`

type GetLikeParams struct {
	UserID     uuid.UUID
	BookmarkID int32
}

func (q *Queries) GetLike(ctx context.Context, arg GetLikeParams) (UsersBookmarksLike, error) {
	row := q.db.QueryRowContext(ctx, getLike, arg.UserID, arg.BookmarkID)
	var i UsersBookmarksLike
	err := row.Scan(
		&i.UserID,
		&i.BookmarkID,
		&i.IsLiked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBookmarksLikes = `-- name: GetUserBookmarksLikes :many

SELECT bookmarks.id FROM bookmarks INNER JOIN
users_bookmarks_likes ON bookmarks.id = users_bookmarks_likes.bookmark_id
WHERE users_bookmarks_likes.user_id = $1 AND users_bookmarks_likes.is_liked = TRUE
`

func (q *Queries) GetUserBookmarksLikes(ctx context.Context, userID uuid.UUID) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getUserBookmarksLikes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeBookmark = `-- name: LikeBookmark :one

INSERT INTO users_bookmarks_likes (user_id, bookmark_id, is_liked)
VALUES ($1, $2, TRUE)
RETURNING user_id, bookmark_id, is_liked, created_at, updated_at
`

type LikeBookmarkParams struct {
	UserID     uuid.UUID
	BookmarkID int32
}

func (q *Queries) LikeBookmark(ctx context.Context, arg LikeBookmarkParams) (UsersBookmarksLike, error) {
	row := q.db.QueryRowContext(ctx, likeBookmark, arg.UserID, arg.BookmarkID)
	var i UsersBookmarksLike
	err := row.Scan(
		&i.UserID,
		&i.BookmarkID,
		&i.IsLiked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlikeBookmark = `-- name: UnlikeBookmark :exec

UPDATE users_bookmarks_likes
SET is_liked = FALSE
WHERE user_id = $1 AND bookmark_id = $2
RETURNING user_id, bookmark_id, is_liked, created_at, updated_at
`

type UnlikeBookmarkParams struct {
	UserID     uuid.UUID
	BookmarkID int32
}

func (q *Queries) UnlikeBookmark(ctx context.Context, arg UnlikeBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, unlikeBookmark, arg.UserID, arg.BookmarkID)
	return err
}

const updateBookmarkLike = `-- name: UpdateBookmarkLike :one

UPDATE users_bookmarks_likes
SET is_liked = $3
WHERE user_id = $1 AND bookmark_id = $2
RETURNING user_id, bookmark_id, is_liked, created_at, updated_at
`

type UpdateBookmarkLikeParams struct {
	UserID     uuid.UUID
	BookmarkID int32
	IsLiked    bool
}

func (q *Queries) UpdateBookmarkLike(ctx context.Context, arg UpdateBookmarkLikeParams) (UsersBookmarksLike, error) {
	row := q.db.QueryRowContext(ctx, updateBookmarkLike, arg.UserID, arg.BookmarkID, arg.IsLiked)
	var i UsersBookmarksLike
	err := row.Scan(
		&i.UserID,
		&i.BookmarkID,
		&i.IsLiked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
